### ISSUE TITLE
[idea] Enhancement to the subtext property to render links

### ISSUE THREAD

**Issue by Salan54** [true3dco/splashgen#6]
Hi,
Would it be possible to have links (https://www.example.com or mailto://john.doe@gmail.com) recognized in the subtext content and rendered accordingly so people could just "click" on the link... 
Thanks a lot

**Comment by traviskaufman** [comment]
Great idea! Are you trying to render links, emails, or both? I can definitely see this for links, but we may want to get a bit fancier and detect the email without needing the `mailto:` scheme for emails.

**Comment by traviskaufman** [comment]
Going to close this for now; if this is still something you need, feel free to let me know and I can reopen :)

**Comment by Salan54** [comment]
Sorry for my late answer...
Yes, I would like to render both links and email. Of course, it would be great to detect xxx.yyy@gmail.com as an email link without the need for the mailto: scheme.
Thanks

**Comment by traviskaufman** [comment]
Got it; thanks for replying!

**Comment by traviskaufman** [comment]
Released in [v0.0.29](https://pypi.org/project/splashgen/) 😄
